version: "{build}"

os: Windows Server 2012 R2

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf true

clone_folder: c:\gopath\src\github.com\CloudyKit\jet

environment:
  GOPATH: c:\gopath
  GO111MODULE: on
  matrix:
    - GOVERSION: 112
    - GOVERSION: 113

install:
  - set PATH=%GOPATH%\bin;c:\go%GOVERSION%\bin;%PATH%
  - set GOROOT=c:\go%GOVERSION%
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env

build: off

test_script:
  - go test -v ./...
  - cd examples/asset_packaging/
  - go run main.go --run-and-exit
  - go get -u github.com/shurcooL/vfsgen
  - go generate
  - go build -tags=deploy_build -o bin/app.exe main.go
  - .\bin\app.exe --run-and-exit
