version: "{build}"

os: Windows Server 2012 R2

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf true

clone_folder: c:\gopath\src\github.com\CloudyKit\jet

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env

build: off

test_script:
  - go test -v ./...
  - cd examples/asset_packaging/
  - go get -u github.com/shurcooL/vfsgen
  - go generate
  - go build -tags=deploy_build -o bin/app main.go
  - cd bin
  - ls -la
  - START /B app.exe
  - ps: $curl = curl http://localhost:9090
  - ps: $curl
  - ps: if ($curl.StatusCode -ne 200) { $host.SetShouldExit(1) }
